Facebook = "" # username only
Flickr = "" # username only
GitHub = "" # username only
Instagram = "" # username only
Linkedin = "" # username only
Microdotblo = "" # username only
Pinterest = "" # username only??
Twitter = "" # username only
YouTube = "" # username only

kofi = "" # username only
patreon = "" # username only

Mastodon = ""  # full url
Website = "" # full url or array of urls
author_hcard = "" # full url
email = "" # address
podcast_website = "" # full url or array of urls
